name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
    
      - name: Install dependencies
        run: dotnet restore GostCryptography.sln
    
      - name: Build
        run: dotnet build GostCryptography.sln --configuration Release --no-restore 
    
      - name: Publish
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
            PROJECT_FILE_PATH: Source/GostCryptography/GostCryptography.csproj
            NUGET_KEY: ${{secrets.NUGET}}
